name: web-test

on: workflow_dispatch

jobs:
  run-web-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      selenium-chrome:
        image: selenium/standalone-chrome:116.0
        options: >-
          --shm-size "2g"
        ports:
          - 4444:4444

    steps:
      - name: store docker image cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        timeout-minutes: 30
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: store docker image cache
        uses: satackey/action-docker-layer-caching@v0.0.11
          # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: execute-web-tests
        run: |
          mvn clean test -Dgroups=web -Dselenide.remote=http://localhost:4444/wd/hub -Dselenide.browser=chrome

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

