name: web-test

on: workflow_dispatch

jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
      - name: pull the project into runner
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Start Selenoid
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status

      - name: execute-web-tests
        run: |
          mvn clean test -Dgroups=web

