name: web-test

on: workflow_dispatch

jobs:
  run-web-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      selenium-chrome:
        image: selenium/standalone-chrome:116.0
        options: >-
          --shm-size "2g"
        ports:
          - 4444:4444

    steps:
      - name: pull the project into runner
        uses: actions/checkout@v4

      - name: setup java jdk11
        timeout-minutes: 30
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: execute-web-tests
        run: |
          mvn clean test -Dgroups=web -Dselenide.remote=http://localhost:4444/wd/hub -Dselenide.browser=chrome

