name: mobile-test

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  run-web-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15


    steps:
      - name: Set up Appium
        run: |
          npm install -g appium@2.0.1
          appium -v
          appium &>/dev/null &

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        timeout-minutes: 30
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: execute-mobile-tests
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          script: mvn clean test -Dgroups=mobile -Dselenide.browser=com.teoke.provider.mobile.MyDemoAppAndroidProvider


      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

